# Generated by Django 5.2.4 on 2025-11-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.CharField(default="no description is here", max_length=1000),
            preserve_default=False,
        ),
    ]
